CREATE OR REPLACE FUNCTION GERAVALORVENDA (
    VAR_VL_CUST IN NUMBER
)
 -- Escopo das variáveis
 -- nome_var tipo := valor;
 RETURN NUMBER IS VAR_VL_VENDA_PRODUTO NUMBER := 0;

TAXA_LUCRO NUMBER := 3.0;

BEGIN
    VAR_VL_VENDA_PRODUTO := VAR_VL_CUST + (VAR_VL_CUST * TAXA_LUCRO);
    RETURN VAR_VL_VENDA_PRODUTO;
END;